# Generated by Django 5.2.4 on 2025-11-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20251009_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Código de Recuperación',
                'verbose_name_plural': 'Códigos de Recuperación',
                'db_table': 'core_codigo_recuperacion',
            },
        ),
    ]
