# Generated by Django 5.2.4 on 2025-11-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color_producto',
            field=models.CharField(max_length=50),
        ),
    ]
