# Generated by Django 5.2.4 on 2025-11-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_color_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(blank=True, null=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('accion', models.CharField(choices=[('added', 'Añadido'), ('edited', 'Editado'), ('deleted', 'Eliminado')], max_length=10)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
