# Generated by Django 5.2.4 on 2025-12-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_historialinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialinventario',
            name='usuario_correo',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
