# Generated by Django 5.2.4 on 2025-11-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_alter_detallefactura_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='hora_expedicion',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
